/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.EmployeeBLL;
import DAL.Employee;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NAT
 */
public class EmployeeListGUI extends javax.swing.JFrame {

    EmployeeBLL employeeBLL = new EmployeeBLL();
    DefaultTableModel model = new DefaultTableModel();
    Employee employeeModel;
    List<Employee> empList;

    /**
     * Creates new form EmployeeList
     */
    public EmployeeListGUI() {
        initComponents();
        String[] colsName = {"Mã Nhân Viên", "Phái", "Số CMND", "Ngày Cấp", "Nơi Cấp", "Số Thẻ", "Họ Tên", "Năm Sinh", "Nơi Sinh",
             "Địa Chỉ Thường Chú", "Địa Chỉ Tạm Trú", "Điện Thoại Thường Trú", "Di Động", "Email", "Ngày Vào Đoàn", "Ngày Vào Đảng",
             "Dân Tộc", "Tôn Giáo", "Quốc Tịch", "Passport", "Ngày Cấp Passport", "Nơi Cấp Passport", "Tình Trạng Hôn Nhân", "Mã Số Thuế",
             "Ngày Cấp MST", "Số Tài Khoản", "Mã Tài Khoản", "Ngân Hàng", "Trình Độ", "Bằng Cấp", "Học Hàm", "Chuyên Môn", "KNLV Chuyên Môn",
             "Loại Nhân Viên", "Đơn Vị", "Phòng Ban", "Bộ Phận", "Chức Danh", "Chức Vụ", "Địa Điểm Làm Việc", "Lương Thử Việc", "Lương CB",
             "Lương KD", "Ngày Vào Cty", "Ngày Hết Hạn TV", "Ngày Vào Chính Thức", "Img"};
        model.setColumnIdentifiers(colsName);
        jTable1.setModel(model);
        setInfoDialog();
        LoadData();
    }

    public void setInfoDialog() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btNew = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btSua = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btXoa = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btThoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Danh sách nhân viên");

        jToolBar1.setRollover(true);

        btNew.setText("Thêm ");
        btNew.setFocusable(false);
        btNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btNew);
        jToolBar1.add(jSeparator1);

        btSua.setText("Sửa");
        btSua.setFocusable(false);
        btSua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        jToolBar1.add(btSua);
        jToolBar1.add(jSeparator2);

        btXoa.setText("Xóa");
        btXoa.setFocusable(false);
        btXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        jToolBar1.add(btXoa);
        jToolBar1.add(jSeparator3);

        jButton4.setText("In");
        jButton4.setEnabled(false);
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator4);

        btThoat.setText("Thoát");
        btThoat.setFocusable(false);
        btThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });
        jToolBar1.add(btThoat);

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16", "Title 17", "Title 18", "Title 19", "Title 20", "Title 21", "Title 22", "Title 23", "Title 24", "Title 25", "Title 26", "Title 27", "Title 28", "Title 29", "Title 30", "Title 31", "Title 32", "Title 33", "Title 34", "Title 35", "Title 36", "Title 37", "Title 38", "Title 39", "Title 40", "Title 41", "Title 42", "Title 43", "Title 44", "Title 45", "Title 46", "Title 47", "Title 48", "Title 49", "Title 50", "Title 51", "Title 52", "Title 53", "Title 54", "Title 55", "Title 56", "Title 57", "Title 58", "Title 59", "Title 60", "Title 61", "Title 62", "Title 63", "Title 64", "Title 65", "Title 66", "Title 67", "Title 68", "Title 69", "Title 70", "Title 71", "Title 72", "Title 73", "Title 74", "Title 75", "Title 76", "Title 77", "Title 78", "Title 79", "Title 80", "Title 81", "Title 82", "Title 83", "Title 84", "Title 85", "Title 86", "Title 87", "Title 88", "Title 89", "Title 90", "Title 91", "Title 92", "Title 93", "Title 94", "Title 95", "Title 96", "Title 97", "Title 98", "Title 99"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewActionPerformed
        
        EmployeeGUI emGui = new EmployeeGUI();
        emGui.setVisible(true);
        Employee newEmployee = emGui.getEmployee();
        if (newEmployee != null) {
            LoadData();
        }
        
    }//GEN-LAST:event_btNewActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:button sua
        int selectedRow = jTable1.getSelectedRow();
        EmployeeGUI emGui = new EmployeeGUI();
        if (selectedRow >= 0) {
//            employeeModel = empList.get(selectedRow);
//            emGui.setEmployee(employeeModel);
            String MaNV = jTable1.getModel().getValueAt(selectedRow, 0).toString();
            String cbPhai = jTable1.getModel().getValueAt(selectedRow, 1).toString();
            String CMND = jTable1.getModel().getValueAt(selectedRow, 2).toString();
            String NgayCapCm = jTable1.getModel().getValueAt(selectedRow, 3).toString();
            String NoiCapCM = jTable1.getModel().getValueAt(selectedRow, 4).toString();
            String Sothe = jTable1.getModel().getValueAt(selectedRow, 5).toString();
            String Hoten = jTable1.getModel().getValueAt(selectedRow, 6).toString();
            String NamSInh = jTable1.getModel().getValueAt(selectedRow, 7).toString();
            String NoiSinh = jTable1.getModel().getValueAt(selectedRow, 8).toString();
            String DiaChiTT = jTable1.getModel().getValueAt(selectedRow, 9).toString();
            String DiaChiTamT = jTable1.getModel().getValueAt(selectedRow, 10).toString();
            String DTTT = jTable1.getModel().getValueAt(selectedRow, 11).toString();
            String DD = jTable1.getModel().getValueAt(selectedRow, 12).toString();
            String EMail = jTable1.getModel().getValueAt(selectedRow, 13).toString();
            String NVD = jTable1.getModel().getValueAt(selectedRow, 14).toString();
            String NVaoD = jTable1.getModel().getValueAt(selectedRow, 15).toString();
            String DT = jTable1.getModel().getValueAt(selectedRow, 16).toString();
            String TG = jTable1.getModel().getValueAt(selectedRow, 17).toString();
            String QT = jTable1.getModel().getValueAt(selectedRow, 18).toString();
            String Passport = jTable1.getModel().getValueAt(selectedRow, 19).toString();
            String NCPP = jTable1.getModel().getValueAt(selectedRow, 20).toString();
            String NCPassP = jTable1.getModel().getValueAt(selectedRow, 21).toString();
            String TTHN = jTable1.getModel().getValueAt(selectedRow, 22).toString();
            String MST = jTable1.getModel().getValueAt(selectedRow, 23).toString();
            String NCMST = jTable1.getModel().getValueAt(selectedRow, 24).toString();
            String STK = jTable1.getModel().getValueAt(selectedRow, 25).toString();
            String MTK = jTable1.getModel().getValueAt(selectedRow, 26).toString();
            String NH = jTable1.getModel().getValueAt(selectedRow, 27).toString();
            String TD = jTable1.getModel().getValueAt(selectedRow, 28).toString();
            String BC = jTable1.getModel().getValueAt(selectedRow, 29).toString();
            String HH = "";
            if(jTable1.getModel().getValueAt(selectedRow, 30) == null){
                 HH = "";
            }else{
                 HH = jTable1.getModel().getValueAt(selectedRow, 30).toString();
            }
            String CM = jTable1.getModel().getValueAt(selectedRow, 31).toString();
            String KNLVCM = jTable1.getModel().getValueAt(selectedRow, 32).toString();
            String LNV = jTable1.getModel().getValueAt(selectedRow, 33).toString();
            String DV = jTable1.getModel().getValueAt(selectedRow, 34).toString();
            String PB = jTable1.getModel().getValueAt(selectedRow, 35).toString();
            String BP = jTable1.getModel().getValueAt(selectedRow, 36).toString();
            String CD = jTable1.getModel().getValueAt(selectedRow, 37).toString();
            String CV = jTable1.getModel().getValueAt(selectedRow, 38).toString();
            String DDLV = jTable1.getModel().getValueAt(selectedRow, 39).toString();
            String LTV = jTable1.getModel().getValueAt(selectedRow, 40).toString();
            String LCB = jTable1.getModel().getValueAt(selectedRow, 41).toString();
            String LKD = jTable1.getModel().getValueAt(selectedRow, 42).toString();
            String NVCT = jTable1.getModel().getValueAt(selectedRow, 43).toString();
            String NHHHD = jTable1.getModel().getValueAt(selectedRow, 44).toString();
            String NVaoCT = jTable1.getModel().getValueAt(selectedRow, 45).toString();          
            emGui.txt_manv.setText(MaNV);
            emGui.cb_phai.setSelectedItem(cbPhai);
            emGui.txt_cmnd.setText(CMND);
            emGui.date_ngaycapCMND.setDateFormatString(NgayCapCm);
            emGui.cb_noicapcmnd.setSelectedItem(NoiCapCM);
            emGui.txt_sothe.setText(Sothe);
            emGui.txt_hoten.setText(Hoten);
            emGui.date_namsinh.setDateFormatString(NamSInh);
            emGui.cb_noisinh.setSelectedItem(NoiSinh);
            emGui.txt_diachithuongtru.setText(DiaChiTT);
            emGui.txt_diachitamtru.setText(DiaChiTamT);
            emGui.txt_dienthoaithuongtru.setText(DTTT);
            emGui.txt_dienthoaididong.setText(DD);
            emGui.txt_email.setText(EMail);
            emGui.date_tongiao.setDateFormatString(NVD);
            emGui.date_ngayvaodang.setDateFormatString(NVaoD);
            emGui.cb_dantoc.setSelectedItem(DT);
            emGui.cb_tongiao.setSelectedItem(TG);
            emGui.cb_quoctich.setSelectedItem(QT);
            emGui.txt_pasport.setText(Passport);
            emGui.date_ngaycappassport.setDateFormatString(NCPP);
            emGui.txt_noicappassport.setText(NCPassP);
            emGui.cb_tthn.setSelectedItem(TTHN);
            emGui.txt_masothue.setText(MST);
            emGui.date_ngaycapmst.setDateFormatString(NCMST);
            emGui.txt_sotaikhoan.setText(STK);
            emGui.txt_mataikhoan.setText(MTK);
            emGui.cb_nganhang.setSelectedItem(NH);
            emGui.cb_trinhdo.setSelectedItem(TD);
            emGui.cb_bangcap.setSelectedItem(BC);
            emGui.txt_hocham.setText(HH);
            emGui.txt_chuyenmon.setText(CM);
            emGui.txt_knchuyenmon_nam.setText(KNLVCM);
            emGui.cb_loainv.setSelectedItem(LNV);
            emGui.cb_donvi.setSelectedItem(DV);
            emGui.cb_phongban.setSelectedItem(PB);
            emGui.cb_bophan.setSelectedItem(BP);
            emGui.cb_chucdanh.setSelectedItem(CD);
            emGui.cb_chucvu.setSelectedItem(CV);
            emGui.cb_diadiemlamviec.setSelectedItem(DDLV);
            emGui.txt_luongthuviec.setText(LTV);
            emGui.txt_luongcoban.setText(LCB);
            emGui.txt_luongkinhdoanh.setText(LKD);
            emGui.date_ngayvaocty.setDateFormatString(NVCT);
            emGui.date_ngayvaochinhthuc.setDateFormatString(NVaoCT);
            emGui.date_ngayhethan.setDateFormatString(NHHHD);
            
            emGui.setVisible(true);
            emGui.btn_luu.setEnabled(false);
        }
//        else{
//            emGui.setVisible(false);
//        }


    }//GEN-LAST:event_btSuaActionPerformed
    private void updateTableEmployee(Employee employeeModel) {
        model.addRow(new Object[0]);
        int row = jTable1.getRowCount() - 1;
        model.setValueAt(employeeModel.getMaNV(), row, 0);
        model.setValueAt(employeeModel.getPhai(), row, 1);
        model.setValueAt(employeeModel.getCMND(), row, 2);
        model.setValueAt(employeeModel.getNgayCapCMND(), row, 3);
        model.setValueAt(employeeModel.getNoiCapCMND(), row, 4);
        model.setValueAt(employeeModel.getSothe(), row, 5);
        model.setValueAt(employeeModel.getHoTen(), row, 6);
        model.setValueAt(employeeModel.getNamSinh(), row, 7);
        model.setValueAt(employeeModel.getNoiSinh(), row, 8);
        model.setValueAt(employeeModel.getDiaChiThuongTru(), row, 9);
        model.setValueAt(employeeModel.getDiaChiTamTru(), row, 10);
        model.setValueAt(employeeModel.getDienThoaiThuongTru(), row, 11);
        model.setValueAt(employeeModel.getDiDong(), row, 12);
        model.setValueAt(employeeModel.getEmail(), row, 13);
        model.setValueAt(employeeModel.getNgayVaoDoan(), row, 14);
        model.setValueAt(employeeModel.getNgayVaoDang(), row, 15);
        model.setValueAt(employeeModel.getDanToc(), row, 16);
        model.setValueAt(employeeModel.getTonGiao(), row, 17);
        model.setValueAt(employeeModel.getQuocTich(), row, 18);
        model.setValueAt(employeeModel.getPassport(), row, 19);
        model.setValueAt(employeeModel.getNgayCapPassport(), row, 20);
        model.setValueAt(employeeModel.getNoiCapPassport(), row, 21);
        model.setValueAt(employeeModel.getTinhTrangHonNhan(), row, 22);
        model.setValueAt(employeeModel.getMaSoThue(), row, 23);
        model.setValueAt(employeeModel.getNgayCapMST(), row, 24);
        model.setValueAt(employeeModel.getSoTaiKhoan(), row, 25);
        model.setValueAt(employeeModel.getMaTaiKhoan(), row, 26);
        model.setValueAt(employeeModel.getNganHang(), row, 27);
        model.setValueAt(employeeModel.getTrinhDo(), row, 28);
        model.setValueAt(employeeModel.getBangCap(), row, 29);
        model.setValueAt(employeeModel.getHocHam(), row, 30);
        model.setValueAt(employeeModel.getChuyenMon(), row, 31);
        model.setValueAt(employeeModel.getKNLVChuyenMon(), row, 32);
        model.setValueAt(employeeModel.getLoaiNhanVien(), row, 33);
        model.setValueAt(employeeModel.getDonVi(), row, 34);
        model.setValueAt(employeeModel.getPhongBan(), row, 35);
        model.setValueAt(employeeModel.getBoPhan(), row, 36);
        model.setValueAt(employeeModel.getChucDanh(), row, 37);
        model.setValueAt(employeeModel.getChucVu(), row, 38);
        model.setValueAt(employeeModel.getDiaDiemLamViec(), row, 39);
        model.setValueAt(employeeModel.getLuongThuViec(), row, 40);
        model.setValueAt(employeeModel.getLuongCB(), row, 41);
        model.setValueAt(employeeModel.getLuongKD(), row, 42);
        model.setValueAt(employeeModel.getNgayVaoCty(), row, 43);
        model.setValueAt(employeeModel.getNgayHetHanTV(), row, 44);
        model.setValueAt(employeeModel.getNgayVaoChinhThuc(), row, 45);
        model.setValueAt(employeeModel.getImg(), row, 46);
    }
    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btThoatActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        int employeeToDelete;
        try {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow >= 0) {
                employeeToDelete =  Integer.valueOf(jTable1.getModel().getValueAt(selectedRow, 0).toString());
                    String message = String.format("Bạn chắc kèo muốn xóa '%s' chứ ?", employeeToDelete);
                    int answer = JOptionPane.showConfirmDialog(this, message, "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
                    
                    if (answer == JOptionPane.OK_OPTION) {
                        employeeBLL.DeleteEmployeeDAL(employeeToDelete);
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        model.removeRow(selectedRow);
                    
                }
            }
        } catch (Exception ex) {
            String message = "Could not delete category. Error:\n" + ex.getMessage();
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked
    private void LoadData() {
        ArrayList<Employee> employeeListModel = employeeBLL.ReadEmployeeBll();
        Employee employeeModel = new Employee();
        for (int i = 0; i < employeeListModel.size(); i++) {
            employeeModel = employeeListModel.get(i);
            model.addRow(new Object[0]);
            model.setValueAt(employeeModel.getMaNV(), i, 0);
            model.setValueAt(employeeModel.getPhai(), i, 1);
            model.setValueAt(employeeModel.getCMND(), i, 2);
            model.setValueAt(employeeModel.getNgayCapCMND(), i, 3);
            model.setValueAt(employeeModel.getNoiCapCMND(), i, 4);
            model.setValueAt(employeeModel.getSothe(), i, 5);
            model.setValueAt(employeeModel.getHoTen(), i, 6);
            model.setValueAt(employeeModel.getNamSinh(), i, 7);
            model.setValueAt(employeeModel.getNoiSinh(), i, 8);
            model.setValueAt(employeeModel.getDiaChiThuongTru(), i, 9);
            model.setValueAt(employeeModel.getDiaChiTamTru(), i, 10);
            model.setValueAt(employeeModel.getDienThoaiThuongTru(), i, 11);
            model.setValueAt(employeeModel.getDiDong(), i, 12);
            model.setValueAt(employeeModel.getEmail(), i, 13);
            model.setValueAt(employeeModel.getNgayVaoDoan(), i, 14);
            model.setValueAt(employeeModel.getNgayVaoDang(), i, 15);
            model.setValueAt(employeeModel.getDanToc(), i, 16);
            model.setValueAt(employeeModel.getTonGiao(), i, 17);
            model.setValueAt(employeeModel.getQuocTich(), i, 18);
            model.setValueAt(employeeModel.getPassport(), i, 19);
            model.setValueAt(employeeModel.getNgayCapPassport(), i, 20);
            model.setValueAt(employeeModel.getNoiCapPassport(), i, 21);
            model.setValueAt(employeeModel.getTinhTrangHonNhan(), i, 22);
            model.setValueAt(employeeModel.getMaSoThue(), i, 23);
            model.setValueAt(employeeModel.getNgayCapMST(), i, 24);
            model.setValueAt(employeeModel.getSoTaiKhoan(), i, 25);
            model.setValueAt(employeeModel.getMaTaiKhoan(), i, 26);
            model.setValueAt(employeeModel.getNganHang(), i, 27);
            model.setValueAt(employeeModel.getTrinhDo(), i, 28);
            model.setValueAt(employeeModel.getBangCap(), i, 29);
            model.setValueAt(employeeModel.getHocHam(), i, 30);
            model.setValueAt(employeeModel.getChuyenMon(), i, 31);
            model.setValueAt(employeeModel.getKNLVChuyenMon(), i, 32);
            model.setValueAt(employeeModel.getLoaiNhanVien(), i, 33);
            model.setValueAt(employeeModel.getDonVi(), i, 34);
            model.setValueAt(employeeModel.getPhongBan(), i, 35);
            model.setValueAt(employeeModel.getBoPhan(), i, 36);
            model.setValueAt(employeeModel.getChucDanh(), i, 37);
            model.setValueAt(employeeModel.getChucVu(), i, 38);
            model.setValueAt(employeeModel.getDiaDiemLamViec(), i, 39);
            model.setValueAt(employeeModel.getLuongThuViec(), i, 40);
            model.setValueAt(employeeModel.getLuongCB(), i, 41);
            model.setValueAt(employeeModel.getLuongKD(), i, 42);
            model.setValueAt(employeeModel.getNgayVaoCty(), i, 43);
            model.setValueAt(employeeModel.getNgayHetHanTV(), i, 44);
            model.setValueAt(employeeModel.getNgayVaoChinhThuc(), i, 45);
            model.setValueAt(employeeModel.getImg(), i, 46);
            //System.out.println("ID GUI" + employeeModel);
        }
        jTable1.setModel(model);
        employeeListModel.clear();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeListGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNew;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
